sync:
  # 启动时，是否先执行一次全量任务？ (true/false)
  run_full_task_on_startup: True

  # 是否启用实时监控？ (true=文件变更时立即处理, false=仅靠定时任务)
  real_time_monitor: True

  cron_full_process:
    # 是否启用定时任务？ (true/false)
    enable: True

    # 定时执行时间 (Cron格式: 分 时 日 月 周)
    # 示例: "0 3 * * *" -> 每天凌晨3点
    cron_expression: "0 3 * * *"

    # 文件处理速率限制 (个/秒)，0为不限制。
    # 用于大量文件时降低磁盘负载。(例: 1=每秒1个, 2=每秒2个)
    files_per_second_limit: 1

    # 定时任务是否扫描所有文件以确保完整性？ (true/false)
    full_generate: True

    # 是否覆盖已存在的目标文件？ (false=仅源文件更新时覆盖, true=总是覆盖)
    overwrite_existing: False

    # 源文件删除后，是否同步删除目标文件？ (true/false)
    sync_source_dest: True

    # 是否自动清理目标目录中的空文件夹？ (true/false)
    cleanup_empty_dirs: True

  monitor_confs:
    - 
      # 源目录列表 (视频/媒体文件所在位置)
      source_dir: ["/mnt/media","/mnt/media2"]

      # 目标输出目录 (生成的.strm和元数据放这里)
      dest_dir: "/mnt/strm"

      # .strm文件内指向的真实路径 (需与Emby/Plex等播放器访问路径一致)
      library_dir: "/mnt/media"

      # 是否生成.strm文件？ (true/false)
      create_strm: True
      
      # 是否同步元数据文件(.nfo, .srt等)？ (true/false)
      copy_metadata: True

      # 需要生成strm的视频后缀
      video_extensions: [
        ".mkv", ".iso", ".ts", ".mp4", ".avi", 
        ".rmvb", ".wmv", ".m2ts", ".mpg", 
        ".flv", ".rm", ".mov", ".m4v", ".webm", ".mpeg"
      ]
      
      # 需要同步的元数据后缀
      metadata_extensions: [
        ".nfo", ".jpg", ".jpeg", ".png", ".svg",
        ".ass", ".srt", ".sup", ".ssa", ".sub",
        ".mp3", ".flac", ".wav", ".aac", ".ogg",
        ".webp", ".bmp", ".gif"
      ]