name: 自动构建 YSTRM 镜像到 GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # 允许推送镜像到GHCR
      contents: read   # 允许读取仓库代码
    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取镜像标签
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.actor }}/ystrm  # 你的GHCR镜像名
          tags: |
            latest
            ${{ github.sha }}  # 用commit哈希做版本标签
          flavor: |
            latest=true

      - name: 构建并推送镜像（适配新CMD路径）
        uses: docker/build-push-action@v5
        with:
          context: .  # 构建上下文：项目根目录（含main.py）
          file: ./Dockerfile  # 正确的Dockerfile路径
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64  # 构建平台（按需加linux/arm64）
          cache-from: type=gha  # 缓存加速
          cache-to: type=gha,mode=max
